#!/usr/bin/env ruby

require "git_curate"
require "optparse"

def main
  parser = GitCurate::CLIParser.new
  continue = parser.parse(ARGV)
  return unless continue

  runner = GitCurate::Runner.new(parser.parsed_options)
  runner.run
rescue OptionParser::InvalidOption
  puts "Unrecognized option"
  puts 'For help, enter `git curate -h`'
  exit(1)
end

main
